name: Build and Deploy React Portfolio

on:
  push:
    branches:
      - terraform_azure_container_apps_02

permissions:
  contents: read
  packages: write
  id-token: write

env:
  RESOURCE_GROUP: ReactStaticWebApp2026_group
  CONTAINER_APP: portfolio-app
  CONTAINER_APP_ENV: portfolio-env
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/reactmaster:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Image
        run: docker push $IMAGE_NAME

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Container Apps Extension
        run: az extension add --name containerapp --upgrade

      # # Step 1 :
      # - name: Check or Create Resource Group
      #   run: |
      #     echo "=== 01: Resource Group Status ==="

      #     if az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
      #       echo "Resource Group already exists"
      #     else
      #       echo "Creating Resource Group..."
      #       az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output table
      #     fi

      #     echo "=== Resource Group List ==="
      #     az group show --name "$RESOURCE_GROUP" --output table || echo "Resource Group not found"


      # # Step 2 :
      # - name: Check or Create Container App Environment
      #   run: |
      #     echo "=== 02: Container App Environment Status ==="
      #     if az containerapp env show --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
      #       echo "Environment already exists"
      #     else
      #       echo "Creating Environment..."
      #       az containerapp env create --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --location eastasia
      #     fi

      #     echo "=== Container App Environment List ==="
      #     az containerapp env show --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --output table || echo "Container App Environment not found"


      # # Step 3 : Container App
      # # - name: Check Container App
      # #   run: |
      # #     echo "=== Container App ==="
      # #     az containerapp show \
      # #       --name $CONTAINER_APP \
      # #       --resource-group $RESOURCE_GROUP \
      # #       --output table || echo "Container App not found"

      # # - name: Ensure Container App Exists
      # #   run: |
      # #     if ! az containerapp show \
      # #       --name $CONTAINER_APP \
      # #       --resource-group $RESOURCE_GROUP >/dev/null 2>&1; then

      # #       echo "Creating Container App..."

      # #       az containerapp create \
      # #         --name $CONTAINER_APP \
      # #         --resource-group $RESOURCE_GROUP \
      # #         --environment $CONTAINER_APP_ENV \
      # #         --image $IMAGE_NAME \
      # #         --target-port 80 \
      # #         --ingress external \
      # #         --cpu 0.25 \
      # #         --memory 0.5Gi

      # #     else
      # #       echo "Updating Container App..."

      # #       az containerapp update \
      # #         --name $CONTAINER_APP \
      # #         --resource-group $RESOURCE_GROUP \
      # #         --image $IMAGE_NAME
      # #     fi


      # # Step 4:
      # - name: List Resources in Resource Group
      #   run: |
      #     echo "=== List Resources in Resource Group ==="
      #     az resource list --resource-group $RESOURCE_GROUP --output table



      # # Step 5:
      # # - name: Deploy Container App
      # #   run: |
      # #     az containerapp up \
      # #       --name $CONTAINER_APP \
      # #       --resource-group $RESOURCE_GROUP \
      # #       --environment $CONTAINER_APP_ENV \
      # #       --image $IMAGE_NAME \
      # #       --target-port 80 \
      # #       --ingress external \
      # #       --cpu 0.25 \
      # #       --memory 0.5Gi

      # # Step 6:
      # # - name: Show URL
      # #   run: |
      # #     az containerapp show \
      # #       --name $CONTAINER_APP \
      # #       --resource-group $RESOURCE_GROUP \
      # #       --query properties.configuration.ingress.fqdn \
      # #       -o tsv


      # - name: Wait 30 Minutes
      #   run: sleep 180

      # - name: Delete Container App
      #   run: |
      #     echo "== 01: Delete Container App =="
      #     if az containerapp show --name "$CONTAINER_APP" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
      #       if az containerapp delete --name "$CONTAINER_APP" --resource-group "$RESOURCE_GROUP" --yes; then
      #         echo "✅ Container App deleted successfully"
      #       else
      #         echo "❌ Failed to delete Container App"
      #         exit 1
      #       fi
      #     else
      #       echo "ℹ️ Container App does not exist"
      #     fi


      # - name: Delete Container App Environment
      #   run: |
      #     echo "== 02: Delete Container App Environment =="
      #     if az containerapp env show --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
      #       if az containerapp env delete --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --yes; then
      #         echo "✅ Container App Environment deleted successfully"
      #       else
      #         echo "❌ Failed to delete Container App Environment"
      #         exit 1
      #       fi
      #     else
      #       echo "ℹ️ Container App Environment does not exist"
      #     fi


      # - name: Delete Log Analytics Workspace (Dynamic)
      #   run: |
      #     echo "== 04: Delete Log Analytics Workspace =="
      #     # Get first workspace name in the resource group
      #     WORKSPACE_NAME=$(az monitor log-analytics workspace list \
      #       --resource-group "$RESOURCE_GROUP" \
      #       --query "[0].name" -o tsv)

      #     if [ -z "$WORKSPACE_NAME" ]; then
      #       echo "ℹ️ No Log Analytics Workspace found"
      #       exit 0
      #     fi

      #     echo "Found Workspace: $WORKSPACE_NAME"

      #     if az monitor log-analytics workspace show \
      #       --workspace-name "$WORKSPACE_NAME" \
      #       --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then

      #       if az monitor log-analytics workspace delete \
      #         --workspace-name "$WORKSPACE_NAME" \
      #         --resource-group "$RESOURCE_GROUP" \
      #         --yes; then
      #         echo "✅ Log Analytics Workspace deleted successfully"
      #       else
      #         echo "❌ Failed to delete Log Analytics Workspace"
      #         exit 1
      #       fi
      #     else
      #       echo "ℹ️ Workspace not found (already deleted?)"
      #     fi


      # Check All Deletion Completed
      - name: Set Subscription
        run: |
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Log Analytics Workspace List
        run: |
          echo "== 04: Log Analytics Workspace List =="

          COUNT=$(az monitor log-analytics workspace list \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            --query "length(@)" -o tsv)

          if [ "$COUNT" -eq 0 ]; then
            echo "ℹ️ No Log Analytics Workspaces found"
          else
            az monitor log-analytics workspace list \
              --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
              --output table
          fi

      - name: List Container App Environments
        run: |
          echo "== Container App Environments =="

          RESULT=$(az containerapp env list --output table)

          if [ -z "$RESULT" ] || [ "$RESULT" = "[]" ]; then
            echo "ℹ️ No Container App Environments found"
          else
            echo "$RESULT"
          fi


      - name: List Container Apps
        run: |
          echo "== Container Apps =="

          RESULT=$(az containerapp list --output table)

          if [ -z "$RESULT" ] || [ "$RESULT" = "[]" ]; then
            echo "ℹ️ No Container Apps found"
          else
            echo "$RESULT"
          fi